version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 6030c082dd061c9db240bf8843482feda35322decaad846163cbb4818c1685c3

    working_directory: ~/slovensko-digital/redflags.slovensko.digital

    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          RAILS_ENV: test

      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./test-reporter
      - run: chmod +x ./test-reporter
      - run: echo "deb http://apt.postgresql.org/pub/repos/apt stretch-pgdg main" | sudo tee -a /etc/apt/sources.list.d/pgdg.list
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-10
      - restore_cache: { keys: ['{{ checksum "Gemfile.lock" }}'] }
      - run: gem install bundler
      - run: gem update --system
      - run: bundle install --path vendor/bundle
      - save_cache: { key: '{{ checksum "Gemfile.lock" }}', paths: [vendor/bundle] }
      - run: dockerize -wait tcp://localhost:5432 -timeout 60s
      - run: mv .circleci/database.yml config/database.yml
      - run: bundle exec rake db:create db:schema:load --trace
      - run: ./test-reporter before-build
      - run: bundle exec rspec
      - run: ./test-reporter after-build --coverage-input-type simplecov --exit-code $?
